# Jobs for sfdx-core
jobs:
  - name: unittest
    script: scripts/jenkins/unittest.groovy
  # Use the default promote script
  - name: publish
    testTarget: test-with-coverage
    envMap:
      - 'SFDX_USE_GENERIC_UNIX_KEYCHAIN': true
        'EMAIL': 't.dvornik@salesforce.com'
  - name: publish-jsdoc
    script: scripts/jenkins/release-doc.groovy
    branches:
      - tnoonan/master
    envMap:
      -
        releaseType: STAGE

  - name: promote--jsdoc
    script: scripts/jenkins/release-doc.groovy
    branches:
      - tnoonan/master
    envMap:
      -
        releaseType: PROD
